Refactor
Allenxuxu/ringbuffer pull request #1
Opened 2019-09-24 17:53 UTC by Harold2017

## Refactor

- short branch with early break
- remove redundant vars and statements

## Suggestion

- rename

```Go
type RingBuffer struct {
	buf      []byte
	cap      uint
	readPtr  uint
	writePtr uint
	isEmpty  bool
}
// RetrieveAll / Retrieve -> ClearAll / Clear
// Length / Free -> BytesAvailableRead / BytesAvailableWrite
// makeSpace -> allocate or addCap
// .etc
```

- refactor atomic_ring_buffer as well

2019-09-25 02:46 UTC, Allenxuxu requested changes

2019-09-25 02:46 UTC, Allenxuxu commented on ring_buffer.go
> +	if r.w == r.r {
非常感谢pr

这边这个分支逻辑，似乎没有必要，而且会漏掉 end

2019-09-25 02:46 UTC, Allenxuxu commented on ring_buffer.go
> +	if r.w == r.r {
同样这边的分支逻辑似乎没有必要

2019-09-25 03:08 UTC, Harold2017 commented on ring_buffer.go
> +	if r.w == r.r {
确实不需要

2019-09-25 06:58 UTC, Allenxuxu requested changes

2019-09-25 06:58 UTC, Allenxuxu commented on ring_buffer.go
> +	if n >= r.size-r.r+r.w {
这边这个 `=` 号 可以去掉

2019-09-25 06:58 UTC, Allenxuxu commented on ring_buffer.go
> +	if len >= r.size-r.r+r.w {
`=` 号建议删除

2019-09-25 06:58 UTC, Allenxuxu commented on ring_buffer.go
> -		if r.isEmpty {
我认为 `if r.isEmpty ` 判断逻辑还是应该放在这里的，因为大多数情况下 `r.w != r.r` ,可以减少一次判断

2019-09-25 06:58 UTC, Allenxuxu commented on ring_buffer.go
> -		if r.isEmpty {
我认为 `if r.isEmpty ` 判断逻辑还是应该放在这里的，因为大多数情况下 `r.w != r.r` ,可以减少一次判断

2019-09-25 06:58 UTC, Allenxuxu commented on ring_buffer.go
> -		if !r.isEmpty {
我认为 `if r.isEmpty ` 判断逻辑还是应该放在这里的，因为大多数情况下 `r.w != r.r` ,可以减少一次判断

2019-09-25 09:23 UTC, Harold2017 commented on ring_buffer.go
> -		if !r.isEmpty {
是的, 我习惯先判断空值了XD

2019-09-26 03:54 UTC, Allenxuxu requested changes

2019-09-26 03:54 UTC, Allenxuxu commented on ring_buffer.go
> -	x := (*[2]uintptr)(unsafe.Pointer(&s))
这边的修改会引发bug，转换后的 []byte cap 值处于未知。

Go 的 string 和 []byte 的底层结构如下：

```go
type StringHeader struct {
	Data uintptr
	Len  int
}
type SliceHeader struct {
	Data uintptr
	Len  int
	Cap  int
}
```

下面的程序，可以运行试试看，就明白了。

```go
package main

import (
	"log"
	"unsafe"
)

func str2bytes2(s string) []byte {
	return *(*[]byte)(unsafe.Pointer(&s))
}

func main() {
	s1 := "100"
	//s2 := "test"
	//log.Println(s2)
	b1 := str2bytes2(s1)
	log.Println(len(b1), cap(b1))
}
```

（ps ：最近比较忙， review 代码只能一点点看，不能一次 review 完请见谅）

2019-09-26 04:52 UTC, Harold2017 commented on ring_buffer.go
> -	x := (*[2]uintptr)(unsafe.Pointer(&s))
转对应ptr的header比uintptr再slice快一些， 不想用引入`reflect`包的话，定义个 `SliceHeader`在包里也可以

2019-09-26 05:56 UTC, Allenxuxu requested changes

2019-09-26 05:56 UTC, Allenxuxu commented on ring_buffer.go
> -	x := (*[2]uintptr)(unsafe.Pointer(&s))
这边保持原有的强制转换方法是没有问题的啊，不需要引入 reflect 包啊

2019-09-26 06:19 UTC, Harold2017 commented on ring_buffer.go
> -	x := (*[2]uintptr)(unsafe.Pointer(&s))
是没问题呀，我是说下面这样少构造一个slice

```Go
func StringToBytes(s string) []byte {
	// return *(*[]byte)(unsafe.Pointer(&s))
	// sh := (*reflect.SliceHeader)(unsafe.Pointer(&s))
	// sh.Cap = sh.Len
	x := (*[3]uintptr)(unsafe.Pointer(&s))
	x[2] = x[1]  // cap = len
	return *(*[]byte)(unsafe.Pointer(&s))
}
```

2019-09-26 11:14 UTC, Allenxuxu requested changes

2019-09-26 11:14 UTC, Allenxuxu commented on ring_buffer.go
> -	x := (*[2]uintptr)(unsafe.Pointer(&s))
这样写，会有严重的bug，

```go
x := (*[3]uintptr)(unsafe.Pointer(&s))
x[2] = x[1]  // cap = len
```
```go
sh := (*reflect.SliceHeader)(unsafe.Pointer(&s))
sh.Cap = sh.Len
```
上面你的两种写法，都存在同一个问题，强制转换使用了不属于 s 这个变量的内存。

```go
type StringHeader struct {
	Data uintptr
	Len  int
}
type SliceHeader struct {
	Data uintptr
	Len  int
	Cap  int
}
```
string 类型的变量，占用内存大小 只有 uintptr + int 这么大小，却强制转换它成为 uintptr + int + int  内存大小的变量，
unsafe.Pointer 并不会检测出这样的错误。

下面的程序可以复限 bug 
```go
package main

import (
	"log"
	"reflect"
	"unsafe"
)

func main() {
	test := struct {
		S1 string
		S2 string
	}{
		"hello",
		"world",
	}

	// 错误 强制转换会使用不属于他的内存
	sh := (*reflect.SliceHeader)(unsafe.Pointer(&test.S1))
	sh.Cap = sh.Len
	b := *(*[]byte)(unsafe.Pointer(&sh))

	// 正确
	//x := (*[2]uintptr)(unsafe.Pointer(&test.S1))
	//h := [3]uintptr{x[0], x[1], x[1]}
	//b := *(*[]byte)(unsafe.Pointer(&h))

	log.Println(len(b), cap(b))
	log.Println(test.S2)
}
```

2019-09-26 11:34 UTC, Harold2017 commented
并不会有bug的，注意我的code里最后cast的还是s，而不是x和sh，你可以试试看

2019-09-26 11:40 UTC, Allenxuxu commented
> 并不会有bug的，注意我的code里最后cast的还是s，而不是x和sh，你可以试试看

举个例子，一个变量大小是4个字节， 你强制转换它为6个字节，还修改了最后两个字节的数据。
Go 不是动态语言，直接操作底层指针，不能随意访问别人的内存的。

我上面例子，使用 struct 包含两个 string，就是为了能让他们的内存连续，好暴露错误。

2019-09-26 12:22 UTC, Harold2017 commented
你说的对，所以我不能cast `x` 或者 `sh`，这是不同的，那改回原来的好了

2019-09-26 12:29 UTC, Allenxuxu commented
嗯嗯， 你push吧。
明天我在 review 下，应该可以合上了。
非常感谢PR来完善这个库😊。

2019-10-11 02:42 UTC, Allenxuxu approved these changes

2019-10-11 02:43 UTC, merged